Disabling wp-calypso default pre-commit commands

diff --git a/bin/pre-commit b/bin/pre-commit
--- a/bin/pre-commit
+++ b/bin/pre-commit
@@ -12,35 +12,35 @@ fi
 pass=true
 
 # i18nlinting.  Just have i18nlint issue warnings for now without failing
-echo "\nValidating translatable strings:\n"
-for file in ${files}; do
-    result=$(./bin/i18nlint --color ${file})
-    if [ $? -ne 0 ]; then
-        echo "\033[31mi18nlint Failed: \033[0m$result"
-        echo "\n -----\n"
-        pass=false
-    else
-        echo "\033[32mi18nlint Passed: ${file}\033[0m"
-    fi
-done
+#echo "\nValidating translatable strings:\n"
+#for file in ${files}; do
+#    result=$(./bin/i18nlint --color ${file})
+#    if [ $? -ne 0 ]; then
+#        echo "\033[31mi18nlint Failed: \033[0m$result"
+#        echo "\n -----\n"
+#        pass=false
+#    else
+#        echo "\033[32mi18nlint Passed: ${file}\033[0m"
+#    fi
+#done
 
-echo "\nValidating .jsx and .js:\n"
+#echo "\nValidating .jsx and .js:\n"
 
-for file in ${files}; do
-    ./node_modules/.bin/eslint ${file}
-    if [ $? -ne 0 ]; then
-        echo "\033[31meslint Failed: ${file}\033[0m"
-        pass=false
-    else
-        echo "\033[32meslint Passed: ${file}\033[0m"
-    fi
-done
+#for file in ${files}; do
+#    ./node_modules/.bin/eslint ${file}
+#    if [ $? -ne 0 ]; then
+#        echo "\033[31meslint Failed: ${file}\033[0m"
+#        pass=false
+#    else
+#        echo "\033[32meslint Passed: ${file}\033[0m"
+#    fi
+#done
 
-echo "\neslint validation complete\n"
+#echo "\neslint validation complete\n"
 
-if ! $pass; then
-    echo "\033[41mCOMMIT FAILED:\033[0m Your commit contains files that should pass validation tests but do not. Please fix the errors and try again.\n"
-    exit 1
-else
-    echo "\033[42mCOMMIT SUCCEEDED\033[0m\n"
-fi
+#if ! $pass; then
+#    echo "\033[41mCOMMIT FAILED:\033[0m Your commit contains files that should pass validation tests but do not. Please fix the errors and try again.\n"
+#    exit 1
+#else
+#    echo "\033[42mCOMMIT SUCCEEDED\033[0m\n"
+#fi
